language: java
jdk:
  - oraclejdk8
  
before_install:
  - chmod +x mvnw
  - mysql -u root -e "CREATE DATABASE ponto_inteligente;"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON PONTO_INTELIGENTE.* TO 'travis'@'localhost';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON PONTO_INTELIGENTE.* TO 'root'@'localhost';"
  #- mysql -u root -e "CREATE USER 'travis'@'localhost' identified by '';"  
  
  
test:
  adapter: mysql2
  database: ponto_inteligente
  username: travis
  encoding: utf8
  
dist: 
  precise